# Generated by Buildr 1.4.12, change to your liking
# Standard maven2 repository
repositories.remote << 'http://repo1.maven.org/maven2'

desc 'filemap'
define 'filemap' do
  project.group = 'com.tooltwist'
  project.version = '0.0.2-SNAPSHOT'
  compile.with 'com.tooltwist:xdata:jar:0.3.2', 'xalan:serializer:jar:2.7.1', 'xalan:xalan:jar:2.7.1', 'xml-apis:xml-apis:jar:1.3.04'
  test.with 'org.hamcrest:hamcrest-core:jar:1.3'
  package :jar, :id => 'filemap'
end
